### ISSUE TITLE
`host` and `port` are ignored for the desktop builds

### ISSUE THREAD

**Issue by chicoxyzzy** [socketsupply/socket#410] opened 2023-05-07 15:08 UTC
We only pass these two values when run on iOS or Android, but they should work for desktop builds as well

**Comment by davidmyersdev** [comment] 2023-09-05 22:02
I'm on macOS, and all absolute paths (e.g. `/path/to/asset.css`) are failing because of the `file://` scheme. In larger applications, using relative paths everywhere is not a simple feat.

**Comment by chicoxyzzy** [comment] 2023-09-05 22:18
@davidmyersdev your issue is unrelated to this one. Please make sure that you allowed `file://*` in the `default-src` of CSP (reference https://github.com/socketsupply/socket/blob/master/test/src/index.html#L5-L11). Please create a new issue if proposed fix doesn't work for you.

**Comment by chicoxyzzy** [comment] 2023-09-06 19:16
Got it. It is fixed on `master` branch. You have to wait for `v0.4` release or build `ssc` from sources.

I'm going to hide these comments as they are unrelated to the topic.

**Comment by chicoxyzzy** [comment] 2023-09-08 12:55
@lamiazar let's keep it in TODO until someone will pick it

**Comment by nnnnathann** [comment] 2023-09-09 20:40
Hi!

After some experimentation with the project, I was able to get the dev server URL working on mac desktop with a few changes to `cli.cc` and `main.cc`:

```diff
diff --git a/src/cli/cli.cc b/src/cli/cli.cc
index 88fce1d5..30ed1ebd 100644
--- a/src/cli/cli.cc
+++ b/src/cli/cli.cc
@@ -2150,7 +2150,7 @@ int main (const int argc, const char* argv[]) {
     settings.insert(std::make_pair("host", devHost));
 
     String devPort = "0";
-    if (optionsWithValue.count("port") > 0) {
+    if (optionsWithValue.count("--port") > 0) {
       devPort = optionsWithValue["--port"];
     }
     settings.insert(std::make_pair("port", devPort));
diff --git a/src/desktop/main.cc b/src/desktop/main.cc
index 1a46db82..b4b25491 100644
--- a/src/desktop/main.cc
+++ b/src/desktop/main.cc
@@ -67,7 +67,7 @@ MAIN {
   static App* app_ptr = &app;
 
   app.setWindowManager(&windowManager);
-  constexpr auto _port = PORT;
+  const auto _port = getDevPort();
 
   const SSC::String OK_STATE = "0";
   const SSC::String ERROR_STATE = "1";
```

Apologies for not submitting a full PR, I feel a little worried about the impact of the changes (didn't fully examine the impact).

Happy to help wherever I can,
nathan

**Comment by jwerle** [comment] 2023-09-09 21:18
> Hi!
> 
> After some experimentation with the project, I was able to get the dev server URL working on mac desktop with a few changes to `cli.cc` and `main.cc`:
> 
> ```diff
> diff --git a/src/cli/cli.cc b/src/cli/cli.cc
> index 88fce1d5..30ed1ebd 100644
> --- a/src/cli/cli.cc
> +++ b/src/cli/cli.cc
> @@ -2150,7 +2150,7 @@ int main (const int argc, const char* argv[]) {
>      settings.insert(std::make_pair("host", devHost));
>  
>      String devPort = "0";
> -    if (optionsWithValue.count("port") > 0) {
> +    if (optionsWithValue.count("--port") > 0) {
>        devPort = optionsWithValue["--port"];
>      }
>      settings.insert(std::make_pair("port", devPort));
> diff --git a/src/desktop/main.cc b/src/desktop/main.cc
> index 1a46db82..b4b25491 100644
> --- a/src/desktop/main.cc
> +++ b/src/desktop/main.cc
> @@ -67,7 +67,7 @@ MAIN {
>    static App* app_ptr = &app;
>  
>    app.setWindowManager(&windowManager);
> -  constexpr auto _port = PORT;
> +  const auto _port = getDevPort();
>  
>    const SSC::String OK_STATE = "0";
>    const SSC::String ERROR_STATE = "1";
> ```
> 
> Apologies for not submitting a full PR, I feel a little worried about the impact of the changes (didn't fully examine the impact).
> 
> Happy to help wherever I can,
> nathan

Hi @nnnnathann,

We'd happily review a PR if you could make one

**Comment by nnnnathann** [comment] 2023-09-10 01:35
Sure, no problem. Created one over here: #565

**Comment by lamiazar** [comment] 2023-09-10 17:17
Fixed by #565

**Closed by lamiazar** 2023-09-10 17:17 UTC
Labels: bug

**Comment by chicoxyzzy** [comment] 2023-09-11 19:54
@davidmyersdev paths like `/path/to/asset.css` should work in `v0.4.0` that we just published. Please try it and create a new issue if you need any help!

**Comment by davidmyersdev** [comment] 2023-10-13 23:31
I finally had a chance to test this again, and I can confirm it works as expected now! Thanks so much!
