### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by mribbons** [socketsupply/socket#197] opened 2023-02-23 07:49 UTC
### What OS are you using (`uname -a`, or Windows version)?
Linux test-socket-ubu-22 5.19.0-32-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### What programming language are you using (C/C++/Go/Rust)?

```
clang++ --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

### What did you expect to see and what you saw instead?
```sh
mkdir app && cd app
ssc init
ssc build -r -o

• using '/home/test/.local/share/socket/' as 'SOCKET_HOME' +0ms
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot copy: No such file or directory [/home/test/app/src/icon.png] [/home/test/app/dist/linux/beepboop-dev_v1.0.0-1_amd64/usr/share/icons/hicolor/256x256/apps/beepboop-dev.png]
Aborted (core dumped)
```

I expected an app to build and run.

**Comment by chicoxyzzy** [comment] 2023-03-24 14:34
closing this one as a duplicate of https://github.com/socketsupply/socket/issues/246

**Closed by chicoxyzzy** 2023-03-24 14:34 UTC
